### ISSUE TITLE
Bug in code

### ISSUE THREAD

**Issue by ladanimesh** [lankerd/GroundworkBundle#10]
https://github.com/lankerd/GroundworkBundle/blob/255a576506d3c50ce3526f560e982adf288451ef/Handler/DataHandler.php#L113

https://github.com/lankerd/GroundworkBundle/blob/255a576506d3c50ce3526f560e982adf288451ef/Handler/DataHandler.php#L114

There is not need to use strtolower function. Because if Entity have field stationAddress it'll convert it into stationaddress and then we can not find its setter getter method and it'll not update record of it.

**Comment by spignataro** [comment]
this looks to be resolved. Can you please confirm and close.

**Comment by lankerd** [comment]
Thank you for pointing that out @ladanimesh!  I'll make sure this is reflected in the dev branch!
